TRABALHODEFINITIVO/Models/Filme.cs
using System.ComponentModel.DataAnnotations;

namespace TRABALHODEFINITIVO.Models
{
    public class Filme
    {
        [Key]

        public int FilmeId { get; set; }

        [Required]
        [MinLength(3)]
        public string Titulo { get; set; }

        public int Ano { get; set; }

        public string Tipo { get; set; }

        public decimal Preco { get; set; }

        public DateTime DataAdquirida { get; set; }

        public decimal ValorCusto { get; set; }

        public string Situacao { get; set; }

        public string Diretor { get; set; }

        public string FotoCapa { get; set; }

        public int GeneroId { get; set; }
        public Genero? Genero { get; set; }

        public List<FilmeAtores> FilmeAtores { get; set; } = new List<FilmeAtores>();
    }
}

TRABALHODEFINITIVO/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TRABALHODEFINITIVO.Data;
using TRABALHODEFINITIVO.Models;

namespace TRABALHODEFINITIVO.Controllers
{
    public class FilmesController : Controller
    {
        private readonly TRABALHODEFINITIVOContext _context;

        public FilmesController(TRABALHODEFINITIVOContext context)
        {
            _context = context;
        }

        // GET: Filmes


        public async Task<IActionResult> Index(string textoBusca)
        {
           
            var tRABALHODEFINITIVOContext = _context.Filme.Include(f => f.Genero);

            var query = _context.Filme.AsQueryable();

            if (!string.IsNullOrEmpty(textoBusca))
            {
                query = query.Where(x => x.Titulo.Contains(textoBusca) 
               

                );
            }

            
            return View(await query.ToListAsync());





        }

       





        // GET: Filmes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .Include(f => f.Genero)
                .FirstOrDefaultAsync(m => m.FilmeId == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filmes/Create
        public IActionResult Create()
        {
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "GeneroId", "GeneroId");
            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmeId,Titulo,Ano,Tipo,Preco,DataAdquirida,ValorCusto,Situacao,Diretor,FotoCapa,GeneroId")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // GET: Filmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmeId,Titulo,Ano,Tipo,Preco,DataAdquirida,ValorCusto,Situacao,Diretor,FotoCapa,GeneroId")] Filme filme)
        {
            if (id != filme.FilmeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.FilmeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // GET: Filmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .Include(f => f.Genero)
                .FirstOrDefaultAsync(m => m.FilmeId == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // POST: Filmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filme.FindAsync(id);
            if (filme != null)
            {
                _context.Filme.Remove(filme);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filme.Any(e => e.FilmeId == id);
        }
    }
}

TRABALHODEFINITIVO/Views/Filmes/Create.cshtml
@model TRABALHODEFINITIVO.Models.Filme

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataAdquirida" class="control-label"></label>
                <input asp-for="DataAdquirida" class="form-control" />
                <span asp-validation-for="DataAdquirida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCusto" class="control-label"></label>
                <input asp-for="ValorCusto" class="form-control" />
                <span asp-validation-for="ValorCusto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Situacao" class="control-label"></label>
                <input asp-for="Situacao" class="form-control" />
                <span asp-validation-for="Situacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diretor" class="control-label"></label>
                <input asp-for="Diretor" class="form-control" />
                <span asp-validation-for="Diretor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoCapa" class="control-label"></label>
                <input asp-for="FotoCapa" class="form-control" />
                <span asp-validation-for="FotoCapa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class ="form-control" asp-items="ViewBag.GeneroId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TRABALHODEFINITIVO/Views/Filmes/Delete.cshtml
@model TRABALHODEFINITIVO.Models.Filme

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataAdquirida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataAdquirida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCusto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCusto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Situacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diretor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diretor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FotoCapa)
        </dt>
        <
        <dd class="col-sm-10">
            <img src="@Model.FotoCapa" height="320px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TRABALHODEFINITIVO/Views/Filmes/Details.cshtml
@model TRABALHODEFINITIVO.Models.Filme

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataAdquirida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataAdquirida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCusto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCusto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Situacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diretor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diretor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FotoCapa)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.FotoCapa" height="320px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FilmeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TRABALHODEFINITIVO/Views/Filmes/Edit.cshtml
@model TRABALHODEFINITIVO.Models.Filme

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmeId" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataAdquirida" class="control-label"></label>
                <input asp-for="DataAdquirida" class="form-control" />
                <span asp-validation-for="DataAdquirida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCusto" class="control-label"></label>
                <input asp-for="ValorCusto" class="form-control" />
                <span asp-validation-for="ValorCusto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Situacao" class="control-label"></label>
                <input asp-for="Situacao" class="form-control" />
                <span asp-validation-for="Situacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diretor" class="control-label"></label>
                <input asp-for="Diretor" class="form-control" />
                <span asp-validation-for="Diretor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoCapa" class="control-label"></label>
                <input asp-for="FotoCapa" class="form-control" />
                <span asp-validation-for="FotoCapa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class="form-control" asp-items="ViewBag.GeneroId"></select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TRABALHODEFINITIVO/Views/Filmes/Index.cshtml
@model IEnumerable<TRABALHODEFINITIVO.Models.Filme>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Filmes" asp-action="Index" method="get">
    <p>
        Título: <input type="text" name="textoBusca" />
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataAdquirida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorCusto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Situacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diretor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FotoCapa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataAdquirida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorCusto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Situacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diretor)
            </td>
             <td>
                    <img src="@item.FotoCapa" height="320px" />
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FilmeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FilmeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FilmeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>