TRABALHODEFINITIVO/Controllers/FilmesAtoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TRABALHODEFINITIVO.Data;
using TRABALHODEFINITIVO.Models;

namespace TRABALHODEFINITIVO.Controllers
{
    public class FilmesAtoresController : Controller
    {
        private readonly TRABALHODEFINITIVOContext _context;

        public FilmesAtoresController(TRABALHODEFINITIVOContext context)
        {
            _context = context;
        }

        // GET: FilmesAtores
        public async Task<IActionResult> Index(string textoBusca)
        {
            var tRABALHODEFINITIVOContext = _context.FilmeAtores.Include(f => f.Ator).Include(f => f.Filme);
            var query = _context.FilmeAtores.AsQueryable();

            if (!string.IsNullOrEmpty(textoBusca))
            {
                query = query.Where(x => x.Personagem.Contains(textoBusca)


                );
            }


            return View(await tRABALHODEFINITIVOContext.ToListAsync());
            
        }

        // GET: FilmesAtores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmeAtores = await _context.FilmeAtores
                .Include(f => f.Ator)
                .Include(f => f.Filme)
                .FirstOrDefaultAsync(m => m.FilmeAtoresId == id);
            if (filmeAtores == null)
            {
                return NotFound();
            }

            return View(filmeAtores);
        }

        // GET: FilmesAtores/Create
        public IActionResult Create()
        {
            ViewData["AtorId"] = new SelectList(_context.Artista, "AtorId", "AtorId");
            ViewData["FilmeId"] = new SelectList(_context.Filme, "FilmeId", "Titulo");
            return View();
        }

        // POST: FilmesAtores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmeAtoresId,FilmeId,AtorId,Personagem")] FilmeAtores filmeAtores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filmeAtores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AtorId"] = new SelectList(_context.Artista, "AtorId", "AtorId", filmeAtores.AtorId);
            ViewData["FilmeId"] = new SelectList(_context.Filme, "FilmeId", "Titulo", filmeAtores.FilmeId);
            return View(filmeAtores);
        }

        // GET: FilmesAtores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmeAtores = await _context.FilmeAtores.FindAsync(id);
            if (filmeAtores == null)
            {
                return NotFound();
            }
            ViewData["AtorId"] = new SelectList(_context.Artista, "AtorId", "AtorId", filmeAtores.AtorId);
            ViewData["FilmeId"] = new SelectList(_context.Filme, "FilmeId", "Titulo", filmeAtores.FilmeId);
            return View(filmeAtores);
        }

        // POST: FilmesAtores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmeAtoresId,FilmeId,AtorId,Personagem")] FilmeAtores filmeAtores)
        {
            if (id != filmeAtores.FilmeAtoresId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filmeAtores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeAtoresExists(filmeAtores.FilmeAtoresId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AtorId"] = new SelectList(_context.Artista, "AtorId", "AtorId", filmeAtores.AtorId);
            ViewData["FilmeId"] = new SelectList(_context.Filme, "FilmeId", "Titulo", filmeAtores.FilmeId);
            return View(filmeAtores);
        }

        // GET: FilmesAtores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filmeAtores = await _context.FilmeAtores
                .Include(f => f.Ator)
                .Include(f => f.Filme)
                .FirstOrDefaultAsync(m => m.FilmeAtoresId == id);
            if (filmeAtores == null)
            {
                return NotFound();
            }

            return View(filmeAtores);
        }

        // POST: FilmesAtores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filmeAtores = await _context.FilmeAtores.FindAsync(id);
            if (filmeAtores != null)
            {
                _context.FilmeAtores.Remove(filmeAtores);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeAtoresExists(int id)
        {
            return _context.FilmeAtores.Any(e => e.FilmeAtoresId == id);
        }
    }
}

TRABALHODEFINITIVO/Views/FilmesAtores/Create.cshtml
@model TRABALHODEFINITIVO.Models.FilmeAtores

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FilmeAtores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FilmeId" class="control-label"></label>
                <select asp-for="FilmeId" class ="form-control" asp-items="ViewBag.FilmeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AtorId" class="control-label"></label>
                <select asp-for="AtorId" class ="form-control" asp-items="ViewBag.AtorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Personagem" class="control-label"></label>
                <input asp-for="Personagem" class="form-control" />
                <span asp-validation-for="Personagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TRABALHODEFINITIVO/Views/FilmesAtores/Delete.cshtml
@model TRABALHODEFINITIVO.Models.FilmeAtores

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FilmeAtores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filme.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ator.AtorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Personagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Personagem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmeAtoresId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TRABALHODEFINITIVO/Views/FilmesAtores/Details.cshtml
@model TRABALHODEFINITIVO.Models.FilmeAtores

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FilmeAtores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filme.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ator.AtorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Personagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Personagem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FilmeAtoresId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TRABALHODEFINITIVO/Views/FilmesAtores/Edit.cshtml
@model TRABALHODEFINITIVO.Models.FilmeAtores

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FilmeAtores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmeAtoresId" />
            <div class="form-group">
                <label asp-for="FilmeId" class="control-label"></label>
                <select asp-for="FilmeId" class="form-control" asp-items="ViewBag.FilmeId"></select>
                <span asp-validation-for="FilmeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AtorId" class="control-label"></label>
                <select asp-for="AtorId" class="form-control" asp-items="ViewBag.AtorId"></select>
                <span asp-validation-for="AtorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Personagem" class="control-label"></label>
                <input asp-for="Personagem" class="form-control" />
                <span asp-validation-for="Personagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TRABALHODEFINITIVO/Views/FilmesAtores/Index.cshtml
@model IEnumerable<TRABALHODEFINITIVO.Models.FilmeAtores>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="FilmesAtores" asp-action="Index" method="get">
    <p>
        Título: <input type="text" name="textoBusca" />
        <input type="submit" value="Filtrar" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Filme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Personagem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Filme.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ator.Nome)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Personagem)
            </td>

            <td>
                <td>
                    <img src="@item.Ator.Foto" height="320px" />
                </td>
            </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Ator.DataNascimento)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Ator.PaisNascimento)
                </td>



            <td>
                <a asp-action="Edit" asp-route-id="@item.FilmeAtoresId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FilmeAtoresId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FilmeAtoresId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>